- api/package-lock.json
- api/src/driver.js
- api/src/queries/GetControlActionByTargetQuery.js
- api/src/resolvers/query.js
- api/src/schema/input.graphql
- api/src/schema/query.graphql
This pull request adds the possibility to query for ControlActions with a given target. This is useful to be able to get all ControlActions that originate from a given EntryPoint. Which can be used by algorithms that use a polling processing mechanism.
```gql
query {
ControlAction(
target: { identifier: "d7a3b614-4c40-413f-99d6-c0da2c844963" }
) {
__typename
identifier
description
actionStatus
}
}
``` 
**TODO:**
> feat(project): allow querying ControlAction by target property

- api/src/queries/SearchQuery.js
When searching using an empty string (initial search), the result was a Lucene parsing error. 
Example query:
```gql
query {
searchResults: searchMetadataText(substring: "", onTypes: [DigitalDocument]) {
... on DigitalDocument {
identifier
title
description
contributor
thumbnailUrl
}
}
}
```
> fix(search): fix parse error when using an empty string

- src/schema/query.graphql
Fixes #19
You can now run the following query:
```
query {
Person (name: "Gustav Mahler") {
identifier
name
}
}
```
> feat(schema): add name param in Person query

- src/resolvers/mutation.js
- src/schema/enum.graphql
- src/schema/interface/CreativeWorkInterface.graphql
- src/schema/type/Article.graphql
- src/schema/type/AudioObject.graphql
- src/schema/type/CreativeWork.graphql
- src/schema/type/DataDownload.graphql
- src/schema/type/Dataset.graphql
- src/schema/type/DigitalDocument.graphql
- src/schema/type/ImageObject.graphql
- src/schema/type/MediaObject.graphql
- src/schema/type/MusicAlbum.graphql
- src/schema/type/MusicComposition.graphql
- src/schema/type/MusicPlaylist.graphql
- src/schema/type/MusicRecording.graphql
- src/schema/type/Review.graphql
- src/schema/type/SoftwareApplication.graphql
- src/schema/type/VideoObject.graphql
These relations are the inverse of each other as described on schema.org, https://schema.org/workExample and https://schema.org/exampleOfWork
We discussed in D2.3 that this would be a better relation between the two items instead of subjectOf, which I initially used.
Set the workExample relation in the schema to be EXAMPLE_OF_WORK with
direction IN so that it's automatically computed if exampleOfWork is set
as a relationship between two items.
Update ThingInterfaceRelationToCreativeWorkInterface to allow
exampleOfWork to be set between Things and CreativeWorks
> Make workExample relation the inverse of exampleOfWork

- src/schema/type/DefinedTerm.graphql
- src/schema/type/DefinedTermSet.graphql
Fixes #88
As part of the development of the Annotation schema, we realised that we needed a way of creating a closed vocabulary of terms that could be used in an annotation, for example if someone wants to annotate a performance as one of (excellent, good, needs work).
@musicog found the [DefinedTerm specification](https://schema.org/DefinedTerm), which is currently on pending.schema.org, but fulfils our requirements.
Add to the schema the ability to create a DefinedTermSet, and add DefinedTerms to it.
> feat(schema): Add DefinedTermSet and DefinedTerm

- src/schema/enum.graphql
- src/schema/interface/MetadataInterface.graphql
- src/schema/interface/ThingInterface.graphql
- src/schema/type/Action.graphql
- src/schema/type/Article.graphql
- src/schema/type/AudioObject.graphql
- src/schema/type/CreativeWork.graphql
- src/schema/type/DataDownload.graphql
- src/schema/type/Dataset.graphql
- src/schema/type/DigitalDocument.graphql
- src/schema/type/EntryPoint.graphql
- src/schema/type/Event.graphql
- src/schema/type/ImageObject.graphql
- src/schema/type/Intangible.graphql
- src/schema/type/MediaObject.graphql
- src/schema/type/MusicAlbum.graphql
- src/schema/type/MusicComposition.graphql
- src/schema/type/MusicGroup.graphql
- src/schema/type/MusicPlaylist.graphql
- src/schema/type/MusicRecording.graphql
- src/schema/type/Organization.graphql
- src/schema/type/Person.graphql
- src/schema/type/Place.graphql
- src/schema/type/Product.graphql
- src/schema/type/Review.graphql
- src/schema/type/SoftwareApplication.graphql
- src/schema/type/VideoObject.graphql
Fixes #81 
As discussed in Amsterdam, make subject optional
When @musicog and I were going through the schema design, we found some cases where it wasn't possible to add a language or name, so we are proposing to make those optional too. I only made name optional in the types that we're using at the moment, because I wasn't sure of the effect of making it optional in some of the other types. We can update this in the future if needed.
> make some fields optional

- .gitignore
- Dockerfile
- package-lock.json
- package.json
I've updated the build and start script since this was still using the `babel-node` script which is [not recommended](https://babeljs.io/docs/en/next/babel-node.html#not-meant-for-production-use) by the creators of Babel.
You can still use `npm run start` to start a debug server with live reload enabled, but for the Docker build and for `node --inspect` you can use the `npm run build:debug` and `npm run start:prod` respectively.
> feat(project): update build and start scripts

- src/transformers/subscriptionFieldTransformer.js
- src/utils/schema.js
- src/utils/schema.test.js
This PR fixes #107 and will prevent `ThingCreateMutation` being triggered for `Delete`, `Merge`, `Update`, `Add` and `Remove` mutations.
> fix(graphql): fix error when deleting non-existing node

- src/schema/type/DefinedTerm.graphql
- src/schema/type/DefinedTermSet.graphql
- src/schema/type/Rating.graphql
A new type which is needed for annotations.
A Rating (https://schema.org/Rating) is an evaluation on a numeric scale, such as 1 to 5 stars.
> feat(schema): Add Rating from schema.org

- src/schema/interface/CreativeWorkInterface.graphql
- src/schema/type/Article.graphql
- src/schema/type/AudioObject.graphql
- src/schema/type/CreativeWork.graphql
- src/schema/type/DataDownload.graphql
- src/schema/type/Dataset.graphql
- src/schema/type/DefinedTermSet.graphql
- src/schema/type/DigitalDocument.graphql
- src/schema/type/ImageObject.graphql
- src/schema/type/MediaObject.graphql
- src/schema/type/MusicAlbum.graphql
- src/schema/type/MusicComposition.graphql
- src/schema/type/MusicPlaylist.graphql
- src/schema/type/MusicRecording.graphql
- src/schema/type/Review.graphql
- src/schema/type/SoftwareApplication.graphql
- src/schema/type/VideoObject.graphql
https://schema.org/isPartOf and https://schema.org/hasPart are the
inverse properties of each other, so their definitions in the schema
should be related
> fix(schema): make isPartOf the inverse of hasPart

- src/commands/RequestControlActionCommand.js
- src/schema/input.graphql
```graphql
mutation {
RequestControlAction(
controlAction: {
entryPointIdentifier: "e63fc3c5-f84e-4a64-9d5b-98a49dd4680c"
potentialActionIdentifier: "b559c52d-6104-4cb3-ab82-39b82bb2de6c"
potentialAction: {
name: "Verify Measures in Beethoven’s 32 Variations"
description: "Within the TROMPA pqroject, we have the vision that more hands will make for lighter work in digitizing and enriching digital music. As an illustration of this vision, here is an example of a running campaign, in which you would be asked to verify whether the musical content in two given measures is the same or not. Can you spot any errors?"
url: "https://trompa-campaign-manager.netlify.com",
creator: "Christiaan",
endTime: "2020-11-12T05:36:23Z"
}
propertyObject: [
{
potentialActionPropertyIdentifier: …
```
> feat(schema): allow creator and endTime properties in RequestControlAction

- src/commands/RequestControlActionCommand.js
Fixes part of #128
PropertyValue.name was incorrectly being set to Property.title.
Still pending is to add wasDerivedFrom to PropertyValue linking to either a Property or a PropertyValueSpecification
⚠️  This change will require updates in all downstream software that queries PropertyValue.name, for example https://github.com/trompamusic/ce-poc-algorithm/blob/1509d3add3c5ec33f9541618ba9fad9c6266c997/algorithm/src/index.js#L352-L353
> copy name field from Property to PropertyValue when using RequestControlAction

- src/schema/type/MusicComposition.graphql
⚠️ There's a bug still present, where neo4j-graphql-js doesn't generate filters for custom scalars. As workExample is `URL` not String, it doesn't generate the filter. Perhaps we'll have to switch all URLs back to Strings
Fixes #132 
Because workExample links to CreativeWorkInterface, we can't use the
auto-generated filters to query a more specific type, e.g.:
MusicComposition(filter:{workExample:{contentUrl_not:null}})
doesn't work because contentUrl is part of MediaObject not CreativeWork.
We add additional fields using the same relation name that point
directly to the concrete types that we use in TROMPA. This means that
the workExample relation still works, but if we need to filter on a
specific Audio/MediaObject field we can. This isn't very sustainable
because we'd have to add it …
> Add EXAMPLE_OF_WORK relations that link directly to Audio/MediaObject

- src/commands/RequestControlActionCommand.js
This is a workaround for a bigger issue in the CE-API. The `identifier` fields are not unique and it is currently possible to have multiple nodes with the same identifier. This will be addressed in an update in the next few days (#141).
Fixes #138
> fix: multiple control actions generated

- src/schema/type/MusicPlaylist.graphql
This PR adds a `trackItemList` property to the `MusicPlaylist` type.
Fixes #126
> fix(MusicPlaylist): add trackItemList property

- src/queries/SearchQuery.js
Improve results drastically when having a typo in the subString.
**Search  MusicCompositions**
```graphql
query {
searchMetadataText(
substring: "Ludwig von Beethoven"
onTypes: [MusicComposition]
onFields: [title]
) {
title
_searchScore
}
}
```
Current results:
```json
{
"data": {
"searchMetadataText": [
{
"title": "32 Variations in C minor",
"_searchScore": 13.919713020324707
},
{
"title": "Magnificat secundi toni",
"_searchScore": 12.121328353881836
},
{
"title": "Magnificat primi toni",
"_searchScore": 12.121328353881836
},
{
"title": "Wilhelmus von Nassaue",
"_searchScore": 11.430655479431152
},
{
"title": "Ännchen von Tharau",
"_searchScore": 11.430655479431152
}
]
}
}
```
Results from this  PR:
```json
{
"data": {
"searchMetadataText": [
{
"title": "O salutaris hostia (Ludwig van …
```
> fix(search): search query improvements

- src/routes/helpers/jsonld/Rating.json
- src/schema/type/Rating.graphql
When we add annotations which are a rating (e.g. scale from 1-10), we need a template so that the annotation tool can render a description and widget to allow a user to create an actual rating.
We do this by creating a Rating template object with name, bestValue, worstValue set to the relevant values, and additionalType set to "https://vocab.trompamusic.eu/vocab#RatingDefinition". This means that ratingValue has to be optional, as it shouldn't be set in the template.
When we create an actual rating by a user, relate it using `prov:wasDerivedFrom` to the template rating
> feat(schema): Add Rating "templates"

- src/migrations/01-constraints.js
- src/schema/enum.graphql
Not all fields were being registered in the full-text migration file. I've updated this so it automatically adds the types and fields based on the schema definition.
> fix(search): register all searchable types with fulltext search dynamically

- src/schema/enum.graphql
- src/schema/type/Annotation.graphql
This replaces #38
In the previous attempt at annotations, we found that it was very difficult to develop a schema that could allow us to define types, add semantic annotations, and then automatically render to json-ld.
As a result, we came up with this new solution, which defines a graphql-specific schema, and then we'll create a specific json-ld serialiser which can convert this schema into json-ld output.
With @musicog, we believe that this schema fits all required annotation types within Trompa. I'm in the process of [documenting the schema](https://docs.google.com/document/d/1B1O2tqaubbEHzXSWhvSDYqYu2lwdNKg4Vy04ukMfrUU/edit?pli=1#), and we'll add this to official documentation soon.
Some items are still pending and need further discussion. I'll mark these in review.
> feat(schema): Add Web Annotations

- src/schema/interface/OrganizationInterface.graphql
- src/schema/type/MusicGroup.graphql
- src/schema/type/Organization.graphql
- src/schema/type/Person.graphql
according to https://schema.org/member the inverse is memberOf, so these relations should use the same relation name in the graphql definition.
This PR does not have to be released urgently.
> feat(schema): make memberOf and member inverses

- src/routes/helpers/jsonld/DefinedTerm.json
- src/schema/type/DefinedTerm.graphql
We use DefinedTermSets to create "Annotation palettes", collections of annotation motivations that are used for a particular annotation task.
The DefinedTerms inside each DefinedTermSet are a special case of an existing web audio motivation (oa:Motivation), and need to be related to that motivation with the property `skos:broader`
> feat(schema): add skos:broader to DefinedTerm
